travis:
  secure:
    BINSTAR_TOKEN: KwSVoLCOs93jZJUusY1LPjB6C3rSMnS0Gcq9imcoaSO6FLUMrRdrQeKKG1YfszpmGePeoK9/g1qWCWbQzhcEeA4HTP6e8kzUhTfEkJfjzHfHVr3RcGNboaO238dLwg6lSP2S6H7ZF1dL/RCeEhZRz5PLsa0hfFQgUKfZHWekUb6d12I9p7As6/42bd3wUe3EEbdZ12iCyb/JQeHmjfcMdSDA0uiSlerQc50dzEbNUTJl/utVcLrcK8tRRVw1dJML3O078tM0MoCK/hXt8azCZlHE37SfBKAHW1xuRRg/bm7t/e7Ch1di6NidHi0ucPQ3i4Bx2BCM0yb5D6W96mgnGvfOE4p4ZNrRRcjbVJHT6vz1oc56nwdm2dhUBwGcIjse1qEJ/lMCb4lN759YEjXd0lT+GSaBmMHzNL6Ltby1ewyRaMXFYRP2hMLzCPEdBwJKU6iqUVe3P8LZwAXE0grinoTRYiNoszu+dI69ZWbgC9zhbOnXndczuExJab4dBVz9z1v8bsLQvy70NV02DIiqlUWOktNekG2bUlaCXrvMCFNFqEcIPSpI/YJ14DB2tDEJN3mFGZGnRGO+d7aAO/VZKR1aigIxvi6WS7YuTGEG/SoAyUswtIgti7wYzhn+9S6ExcWn7qRaz9veo+fkd4Cd+HYgxt5vWcAALNIMpBnIlW0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
